import { expect, test } from "bun:test";
import { cp, mkdir, appendFile, writeFile, readFile, stat, mkdtemp, readdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

import { certifiedRelease, type LaunchSpec, type RuntimeEffects } from "../../src/adapter";
import { initCommand, queuedPrompter, type InitDeps, type InitFsEffects, type QueuedPrompter } from "../../src/cli";
import { loadPack } from "../../src/loader";

const packSourceDir = fileURLToPath(new URL("../../packs/core/l0-tutorial-island/", import.meta.url));

const realFs: InitFsEffects = {
  mkdirp: async (path) => {
    await mkdir(path, { recursive: true });
  },
  writeFile: async (path, content) => {
    await writeFile(path, content, "utf8");
  },
  copyDir: async (source, destination) => {
    await cp(source, destination, { recursive: true });
  },
  appendFile: async (path, content) => {
    await appendFile(path, content, "utf8");
  },
};

function fakeRuntimeEffects(track?: { execs: string[]; installs: number }): RuntimeEffects {
  return {
    exists: () => false,
    mkdirp: async (path) => {
      await mkdir(path, { recursive: true });
    },
    installRuntime: async (request) => {
      if (track) {
        track.installs += 1;
      }
      await mkdir(request.paths.binDir, { recursive: true });
      await writeFile(request.paths.binaryPath, "#!/bin/sh\necho stub\n", { mode: 0o755 });
    },
    execFile: (file) => {
      track?.execs.push(file);
      return { stdout: certifiedRelease.versionOutput, stderr: "", exitCode: 0 };
    },
  };
}

interface HarnessOptions {
  readonly answers: readonly string[];
}

interface InitHarness {
  readonly root: string;
  readonly deps: InitDeps;
  readonly launches: LaunchSpec[];
  readonly prompter: QueuedPrompter;
  readonly track: { execs: string[]; installs: number };
  readonly extensionInstalls: string[];
}

async function makeHarness(options: HarnessOptions): Promise<InitHarness> {
  const root = await mkdtemp(join(tmpdir(), "garnish-init-"));
  const launches: LaunchSpec[] = [];
  const prompter = queuedPrompter(options.answers);
  const track = { execs: [] as string[], installs: 0 };
  const extensionInstalls: string[] = [];

  return {
    root,
    launches,
    prompter,
    track,
    extensionInstalls,
    deps: {
      garnishRootDir: root,
      packSourceDirs: [packSourceDir],
      prompter,
      runtimeEffects: fakeRuntimeEffects(track),
      gateEffects: {
        mkdirp: async (path) => {
          await mkdir(path, { recursive: true });
        },
        writeFile: async (path, content) => {
          await writeFile(path, content, "utf8");
        },
      },
      fs: realFs,
      installExtension: (agentDir) => {
        extensionInstalls.push(agentDir);
      },
      launch: (spec) => {
        launches.push(spec);
      },
      now: () => "2026-07-02T00:00:00Z",
    },
  };
}

test("hermetic E2E: init installs runtime, writes isolated config, activates L0, launches certified binary", async () => {
  const harness = await makeHarness({ answers: ["anthropic", "n", ""] });

  const result = await initCommand(harness.deps);

  expect(result.exitCode).toBe(0);
  expect(harness.track.installs).toBe(1);
  expect(result.runtime.handshake.status).toBe("ok");

  const binary = await stat(result.launchSpec.command);
  expect(binary.isFile()).toBe(true);
  expect(result.launchSpec.command.startsWith(harness.root)).toBe(true);
  expect(result.launchSpec.env.PI_CODING_AGENT_DIR?.startsWith(harness.root)).toBe(true);
  expect(result.launchSpec.env.HOME?.startsWith(harness.root)).toBe(true);
  expect(harness.launches).toHaveLength(1);

  const agentDir = result.runtime.paths.agentDir;
  const config = await readFile(join(agentDir, "config.yml"), "utf8");
  expect(config).toContain("Generated by Garnish");
  expect(config).toContain("apiKeyRef: ANTHROPIC_API_KEY");

  const state = JSON.parse(await readFile(join(agentDir, "garnish", "state.json"), "utf8")) as {
    activeLevel: string;
    runtime: { certifiedVersion: string };
  };
  expect(state.activeLevel).toBe("tutorial-island");
  expect(state.runtime.certifiedVersion).toBe("16.2.13");

  const graph = await loadPack(join(agentDir, "garnish", "packs", "l0-tutorial-island"));
  expect(graph.quests.map((quest) => `${quest.id}`).sort()).toEqual([
    "connect-agent",
    "install-certified-pi",
    "second-turn",
    "status-screen",
  ]);

  const graphFile = JSON.parse(await readFile(join(agentDir, "garnish", "graph.json"), "utf8")) as {
    levels: readonly { id: string }[];
  };
  expect(graphFile.levels.map((level) => level.id)).toEqual(["tutorial-island"]);
  const questsFile = JSON.parse(await readFile(join(agentDir, "garnish", "quests.json"), "utf8")) as readonly {
    id: string;
    checks: readonly unknown[];
  }[];
  expect(questsFile).toHaveLength(4);
  expect(questsFile.every((quest) => quest.checks.length > 0)).toBe(true);
  expect(harness.extensionInstalls).toEqual([agentDir]);

  const sandboxStat = await stat(result.sandboxDir);
  expect(sandboxStat.isDirectory()).toBe(true);
  expect(result.sandboxDir.startsWith(harness.root)).toBe(true);
});

test("interactive onboarding uses at most five prompts (observed: three)", async () => {
  const harness = await makeHarness({ answers: ["anthropic", "n", ""] });

  const result = await initCommand(harness.deps);

  expect(result.promptCount).toBeLessThanOrEqual(5);
  expect(result.promptCount).toBe(3);
  expect(harness.prompter.askedQuestions).toHaveLength(3);
});

test("provider paths: anthropic, openai, and manual other persist env-var references, never raw keys", async () => {
  const cases = [
    { answer: "anthropic", envVar: "ANTHROPIC_API_KEY" },
    { answer: "openai", envVar: "OPENAI_API_KEY" },
    { answer: "other:MY_LOCAL_KEY", envVar: "MY_LOCAL_KEY" },
  ] as const;

  for (const { answer, envVar } of cases) {
    const harness = await makeHarness({ answers: [answer, "n", ""] });
    process.env[envVar] = "sk-super-secret-raw-key";
    try {
      const result = await initCommand(harness.deps);

      expect(result.providerEnvVar).toBe(envVar);
      const config = await readFile(join(result.runtime.paths.agentDir, "config.yml"), "utf8");
      expect(config).toContain(`apiKeyRef: ${envVar}`);
      expect(config).not.toContain("sk-super-secret-raw-key");
    } finally {
      delete process.env[envVar];
    }
  }
});

test("speedrun mode unlocks ahead without XP; Speedrunner badge stays earnable", async () => {
  const harness = await makeHarness({ answers: ["anthropic", "all", ""] });

  const result = await initCommand(harness.deps);

  expect(result.speedrunUnlocks.length).toBeGreaterThan(0);
  expect(result.speedrunUnlocks.every((event) => event.reason === "speedrun")).toBe(true);
  expect(result.speedrunUnlocks.some((event) => event.type !== "unlock")).toBe(false);

  const eventsFile = await readFile(
    join(result.runtime.paths.agentDir, "garnish", "events.jsonl"),
    "utf8",
  );
  const parsed = eventsFile
    .trim()
    .split("\n")
    .map((line) => JSON.parse(line) as { type: string; reason?: string });
  expect(parsed.every((event) => event.type === "unlock" && event.reason === "speedrun")).toBe(true);
  expect(parsed.some((event) => event.type === "xp_award")).toBe(false);
  expect(result.text).toContain("Speedrunner badge");
});

test("non-interactive piped answers drive the same provisioning path", async () => {
  const interactive = await makeHarness({ answers: ["openai", "n", ""] });
  const piped = await makeHarness({ answers: ["openai", "n", ""] });

  const first = await initCommand(interactive.deps);
  const second = await initCommand(piped.deps);

  expect(second.exitCode).toBe(first.exitCode);
  expect(second.providerEnvVar).toBe(first.providerEnvVar);
  expect(second.promptCount).toBe(first.promptCount);

  const firstConfig = await readFile(join(first.runtime.paths.agentDir, "config.yml"), "utf8");
  const secondConfig = await readFile(join(second.runtime.paths.agentDir, "config.yml"), "utf8");
  expect(secondConfig).toBe(firstConfig);
});

test("init isolation: every write lands under the garnish root, none under the user's ~/.omp", async () => {
  const harness = await makeHarness({ answers: ["anthropic", "n", ""] });
  const home = process.env.HOME ?? "";
  const userOmp = join(home, ".omp");
  const before = await dirSignature(userOmp);

  const result = await initCommand(harness.deps);

  expect(result.exitCode).toBe(0);
  const after = await dirSignature(userOmp);
  expect(after.entries).toEqual(before.entries);
  expect(after.configMtime).toBe(before.configMtime);

  expect(harness.track.execs.every((file) => file.startsWith(harness.root))).toBe(true);
});

async function dirSignature(path: string): Promise<{ entries: readonly string[]; configMtime: number }> {
  const entries = await readdir(path).catch(() => [] as string[]);
  const configMtime = await stat(join(path, "agent", "config.yml"))
    .then((s) => s.mtimeMs)
    .catch(() => -1);
  return { entries: [...entries].sort((a, b) => a.localeCompare(b)), configMtime };
}
