import { isAbsolute, join, relative, resolve } from "node:path";

import type { FeatureId } from "../core";
import type { ProgressionUnlockSet } from "../progression";
import type { RuntimePaths } from "./types";

export type GateApprovalMode = "always-ask" | "write" | "yolo";

export type GateSurface =
  | { readonly kind: "tool"; readonly name: string }
  | { readonly kind: "skill"; readonly glob: string }
  | { readonly kind: "mcpServer"; readonly name: string }
  | { readonly kind: "extension"; readonly id: string }
  | { readonly kind: "provider"; readonly id: string }
  | { readonly kind: "approvalMode"; readonly mode: GateApprovalMode };

export type GateCatalog = Readonly<Record<string, readonly GateSurface[]>>;
export type GateCapability =
  | `tool:${string}`
  | `skill:${string}`
  | `mcp:${string}`
  | `extension:${string}`
  | `provider:${string}`
  | `approvalMode:${GateApprovalMode}`;

export type GateConfigData = Readonly<Record<string, unknown>>;

export interface GateMcpConfigData {
  readonly $schema: typeof mcpSchemaUrl;
  readonly garnish: GeneratedByGarnishMarker;
  readonly mcpServers: Readonly<Record<string, never>>;
  readonly disabledServers: readonly string[];
}

export interface RenderedGateConfig {
  readonly configPath: "config.yml";
  readonly mcpPath: "mcp.json";
  readonly config: GateConfigData;
  readonly mcp: GateMcpConfigData;
  readonly configYml: string;
  readonly mcpJson: string;
}

export interface GateConfigEffects {
  readonly mkdirp: (path: string) => void | Promise<void>;
  readonly writeFile: (path: string, content: string) => void | Promise<void>;
}

export interface GateParityIssue {
  readonly capability: GateCapability;
  readonly reason: string;
}

export interface GateParityComparison {
  readonly ok: boolean;
  readonly issues: readonly GateParityIssue[];
}

export interface GateMonotonicityViolation {
  readonly fromIndex: number;
  readonly toIndex: number;
  readonly capability: GateCapability;
}

interface GeneratedByGarnishMarker {
  readonly owner: "garnish";
  readonly generated: true;
  readonly arraysReplaceWholesale: readonly string[];
}

type CatalogSurfaceEntry = {
  readonly featureId: string;
  readonly surface: GateSurface;
  readonly capability: GateCapability;
};

type MutableRecord = Record<string, unknown>;

const mcpSchemaUrl = "https://raw.githubusercontent.com/can1357/oh-my-pi/main/packages/coding-agent/src/config/mcp-schema.json";
const generatedHeader = "# Generated by Garnish. Do not edit; Garnish owns these arrays and replaces them wholesale.\n";
const generatedMarker: GeneratedByGarnishMarker = {
  owner: "garnish",
  generated: true,
  arraysReplaceWholesale: [
    "disabledExtensions",
    "disabledProviders",
    "skills.includeSkills",
    "mcp.disabledServers",
  ],
};

export const v1GateCatalog = {
  "context": [
    { kind: "provider", id: "agents-md" },
    { kind: "provider", id: "claude" },
    { kind: "provider", id: "codex" },
    { kind: "provider", id: "cursor" },
    { kind: "provider", id: "gemini" },
    { kind: "provider", id: "github" },
    { kind: "provider", id: "native" },
    { kind: "provider", id: "opencode" },
  ],
  "extensions": [{ kind: "extension", id: "extension-module:garnish-demo" }],
  "mcp": [{ kind: "mcpServer", name: "garnish-demo" }],
  "skills": [{ kind: "skill", glob: "*" }],
  "subagents": [{ kind: "tool", name: "task" }],
  "tool:bash": [{ kind: "tool", name: "bash" }],
  "tool:file": [
    { kind: "tool", name: "edit" },
    { kind: "tool", name: "glob" },
    { kind: "tool", name: "grep" },
    { kind: "tool", name: "read" },
    { kind: "tool", name: "write" },
  ],
  "tool:shell": [{ kind: "tool", name: "bash" }],
} as const satisfies GateCatalog;

export function renderGateConfig(
  unlockSet: ProgressionUnlockSet,
  catalog: GateCatalog = v1GateCatalog,
): RenderedGateConfig {
  const unlockedFeatures = new Set(unlockSet.features.map((featureId) => `${featureId}`));
  const entries = catalogSurfaceEntries(catalog);
  const unlockedCapabilities = unlockedCapabilitySet(entries, unlockedFeatures);
  const config: MutableRecord = {
    garnish: generatedMarker,
  };

  for (const toolName of uniqueSorted(entries.flatMap((entry) => entry.surface.kind === "tool" ? [entry.surface.name] : []))) {
    setConfigValue(config, toolConfigPath(toolName), unlockedCapabilities.has(`tool:${toolName}`));
  }

  const skillGlobs = uniqueSorted(entries.flatMap((entry) => entry.surface.kind === "skill" ? [entry.surface.glob] : []));
  if (skillGlobs.length > 0) {
    const includeSkills = skillGlobs.filter((glob) => unlockedCapabilities.has(skillCapability(glob)));
    config.skills = {
      enabled: includeSkills.length > 0,
      includeSkills,
    };
  }

  const providers = uniqueSorted(entries.flatMap((entry) => entry.surface.kind === "provider" ? [entry.surface.id] : []));
  if (providers.length > 0) {
    config.disabledProviders = providers.filter((provider) => !unlockedCapabilities.has(providerCapability(provider)));
  }

  const extensionIds = uniqueSorted(entries.flatMap((entry) => entry.surface.kind === "extension" ? [normalizedDisabledExtensionId(entry.surface.id)] : []));
  if (extensionIds.length > 0) {
    config.disabledExtensions = extensionIds.filter((extensionId) => !unlockedCapabilities.has(extensionCapability(extensionId)));
  }

  const mcpServers = uniqueSorted(entries.flatMap((entry) => entry.surface.kind === "mcpServer" ? [entry.surface.name] : []));
  if (mcpServers.length > 0) {
    config.mcp = {
      enableProjectConfig: mcpServers.some((server) => unlockedCapabilities.has(mcpCapability(server))),
    };
  }

  const approvalModes = entries.flatMap((entry) => entry.surface.kind === "approvalMode" ? [entry.surface.mode] : []);
  const unlockedApprovalModes = approvalModes.filter((mode) => unlockedCapabilities.has(approvalModeCapability(mode)));
  if (approvalModes.length > 0) {
    setConfigValue(config, ["tools", "approvalMode"], strongestApprovalMode(unlockedApprovalModes));
  }

  const mcp: GateMcpConfigData = {
    $schema: mcpSchemaUrl,
    garnish: generatedMarker,
    mcpServers: {},
    disabledServers: mcpServers.filter((server) => !unlockedCapabilities.has(mcpCapability(server))),
  };

  return {
    configPath: "config.yml",
    mcpPath: "mcp.json",
    config,
    mcp,
    configYml: `${generatedHeader}${stableYaml(config)}`,
    mcpJson: stableJson(mcp),
  };
}

export async function writeGateConfig(
  paths: RuntimePaths,
  rendered: RenderedGateConfig,
  effects: GateConfigEffects,
): Promise<void> {
  const agentDir = resolve(paths.agentDir);
  const writes = [
    { path: join(agentDir, rendered.configPath), content: rendered.configYml },
    { path: join(agentDir, rendered.mcpPath), content: rendered.mcpJson },
  ] as const;

  for (const write of writes) {
    assertGateWritePathUnderAgentDir(agentDir, write.path);
  }

  await effects.mkdirp(agentDir);
  for (const write of writes) {
    await effects.writeFile(write.path, write.content);
  }
}

export function assertGateWritePathUnderAgentDir(agentDir: string, candidate: string): void {
  if (!isUnderRoot(agentDir, candidate)) {
    throw new Error(`Gate config path escapes Garnish agent dir: ${candidate}`);
  }
}

export function stockParityConfig(catalog: GateCatalog = v1GateCatalog): RenderedGateConfig {
  return renderGateConfig({ features: catalogFeatureIds(catalog), levels: [] }, catalog);
}

export function compareStockParityConfig(
  rendered: RenderedGateConfig,
  catalog: GateCatalog = v1GateCatalog,
): GateParityComparison {
  const enabled = new Set(enabledGateCapabilities(rendered, catalog));
  const issues: GateParityIssue[] = [];
  const seen = new Set<GateCapability>();

  for (const entry of catalogSurfaceEntries(catalog)) {
    if (seen.has(entry.capability)) {
      continue;
    }
    seen.add(entry.capability);
    if (!enabled.has(entry.capability)) {
      issues.push({
        capability: entry.capability,
        reason: "catalog surface is still locked in stock-parity config",
      });
    }
  }

  return {
    ok: issues.length === 0,
    issues,
  };
}

export function enabledGateCapabilities(
  rendered: RenderedGateConfig,
  catalog: GateCatalog = v1GateCatalog,
): readonly GateCapability[] {
  const capabilities: GateCapability[] = [];
  const seen = new Set<GateCapability>();

  for (const entry of catalogSurfaceEntries(catalog)) {
    if (seen.has(entry.capability)) {
      continue;
    }
    seen.add(entry.capability);
    if (isCapabilityEnabled(rendered, entry.surface)) {
      capabilities.push(entry.capability);
    }
  }

  return capabilities.sort(compareString);
}

export function findGateMonotonicityViolations(
  renderedConfigs: readonly RenderedGateConfig[],
  catalog: GateCatalog = v1GateCatalog,
): readonly GateMonotonicityViolation[] {
  const violations: GateMonotonicityViolation[] = [];
  let previous = new Set<GateCapability>();

  for (let index = 0; index < renderedConfigs.length; index += 1) {
    const current = new Set(enabledGateCapabilities(renderedConfigs[index]!, catalog));
    if (index > 0) {
      for (const capability of previous) {
        if (!current.has(capability)) {
          violations.push({
            fromIndex: index - 1,
            toIndex: index,
            capability,
          });
        }
      }
    }
    previous = current;
  }

  return violations;
}

export function catalogFeatureIds(catalog: GateCatalog = v1GateCatalog): FeatureId[] {
  return Object.keys(catalog).sort(compareString) as FeatureId[];
}

function catalogSurfaceEntries(catalog: GateCatalog): CatalogSurfaceEntry[] {
  return Object.keys(catalog)
    .sort(compareString)
    .flatMap((featureId) =>
      [...(catalog[featureId] ?? [])]
        .map(normalizedSurface)
        .sort((left, right) => surfaceCapability(left).localeCompare(surfaceCapability(right)))
        .map((surface) => ({
          featureId,
          surface,
          capability: surfaceCapability(surface),
        })),
    );
}

function unlockedCapabilitySet(entries: readonly CatalogSurfaceEntry[], unlockedFeatures: ReadonlySet<string>): ReadonlySet<GateCapability> {
  const unlocked = new Set<GateCapability>();
  for (const entry of entries) {
    if (unlockedFeatures.has(entry.featureId)) {
      unlocked.add(entry.capability);
    }
  }
  return unlocked;
}

function normalizedSurface(surface: GateSurface): GateSurface {
  if (surface.kind === "extension") {
    return { kind: "extension", id: normalizedDisabledExtensionId(surface.id) };
  }
  return surface;
}

function surfaceCapability(surface: GateSurface): GateCapability {
  switch (surface.kind) {
    case "tool":
      return toolCapability(surface.name);
    case "skill":
      return skillCapability(surface.glob);
    case "mcpServer":
      return mcpCapability(surface.name);
    case "extension":
      return extensionCapability(normalizedDisabledExtensionId(surface.id));
    case "provider":
      return providerCapability(surface.id);
    case "approvalMode":
      return approvalModeCapability(surface.mode);
  }
}

function isCapabilityEnabled(rendered: RenderedGateConfig, surface: GateSurface): boolean {
  switch (surface.kind) {
    case "tool":
      return getConfigValue(rendered.config, toolConfigPath(surface.name)) === true;
    case "skill":
      return skillGlobEnabled(rendered.config, surface.glob);
    case "mcpServer":
      return mcpServerEnabled(rendered, surface.name);
    case "extension":
      return !stringArray(rendered.config.disabledExtensions).includes(normalizedDisabledExtensionId(surface.id));
    case "provider":
      return !stringArray(rendered.config.disabledProviders).includes(surface.id);
    case "approvalMode":
      return approvalModeAllows(getConfigValue(rendered.config, ["tools", "approvalMode"]), surface.mode);
  }
}

function skillGlobEnabled(config: GateConfigData, glob: string): boolean {
  const skills = recordValue(config.skills);
  if (skills?.enabled !== true) {
    return false;
  }
  const includeSkills = stringArray(skills.includeSkills);
  return includeSkills.includes("*") || includeSkills.includes(glob);
}

function mcpServerEnabled(rendered: RenderedGateConfig, server: string): boolean {
  const mcpConfig = recordValue(rendered.config.mcp);
  return mcpConfig?.enableProjectConfig === true && !rendered.mcp.disabledServers.includes(server);
}

function approvalModeAllows(value: unknown, required: GateApprovalMode): boolean {
  if (value !== "always-ask" && value !== "write" && value !== "yolo") {
    return false;
  }
  return approvalModeRank(value) >= approvalModeRank(required);
}

function strongestApprovalMode(modes: readonly GateApprovalMode[]): GateApprovalMode {
  return [...modes].sort((left, right) => approvalModeRank(right) - approvalModeRank(left))[0] ?? "always-ask";
}

function approvalModeRank(mode: GateApprovalMode): number {
  switch (mode) {
    case "always-ask":
      return 0;
    case "write":
      return 1;
    case "yolo":
      return 2;
  }
}

function toolConfigPath(toolName: string): readonly string[] {
  const parts = toolName.split(".");
  if (parts.length > 1) {
    return parts;
  }
  return [toolName, "enabled"];
}

function setConfigValue(config: MutableRecord, path: readonly string[], value: unknown): void {
  let cursor = config;
  for (const part of path.slice(0, -1)) {
    const existing = cursor[part];
    if (recordValue(existing) === undefined) {
      const next: MutableRecord = {};
      cursor[part] = next;
      cursor = next;
    } else {
      cursor = existing as MutableRecord;
    }
  }
  cursor[path[path.length - 1]!] = value;
}

function getConfigValue(config: GateConfigData, path: readonly string[]): unknown {
  let cursor: unknown = config;
  for (const part of path) {
    const record = recordValue(cursor);
    if (record === undefined) {
      return undefined;
    }
    cursor = record[part];
  }
  return cursor;
}

function recordValue(value: unknown): MutableRecord | undefined {
  return typeof value === "object" && value !== null && !Array.isArray(value) ? value as MutableRecord : undefined;
}

function stringArray(value: unknown): string[] {
  return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : [];
}

function toolCapability(toolName: string): GateCapability {
  return `tool:${toolName}`;
}

function skillCapability(glob: string): GateCapability {
  return `skill:${glob}`;
}

function mcpCapability(server: string): GateCapability {
  return `mcp:${server}`;
}

function extensionCapability(extensionId: string): GateCapability {
  return `extension:${extensionId}`;
}

function providerCapability(provider: string): GateCapability {
  return `provider:${provider}`;
}

function approvalModeCapability(mode: GateApprovalMode): GateCapability {
  return `approvalMode:${mode}`;
}

function normalizedDisabledExtensionId(id: string): string {
  return id.includes(":") ? id : `extension-module:${id}`;
}

function stableYaml(value: unknown): string {
  const record = recordValue(value);
  if (record === undefined) {
    throw new Error("Gate config YAML root must be a mapping");
  }
  return `${yamlObjectLines(record, 0).join("\n")}\n`;
}

function yamlObjectLines(record: MutableRecord, indent: number): string[] {
  return Object.keys(record).sort(compareString).flatMap((key) => yamlKeyValueLines(key, record[key], indent));
}

function yamlKeyValueLines(key: string, value: unknown, indent: number): string[] {
  const pad = " ".repeat(indent);
  const renderedKey = yamlKey(key);
  if (isScalar(value)) {
    return [`${pad}${renderedKey}: ${yamlScalar(value)}`];
  }
  if (Array.isArray(value)) {
    if (value.length === 0) {
      return [`${pad}${renderedKey}: []`];
    }
    return [
      `${pad}${renderedKey}:`,
      ...value.flatMap((item) => yamlArrayItemLines(item, indent + 2)),
    ];
  }
  const record = recordValue(value);
  if (record !== undefined) {
    const keys = Object.keys(record);
    if (keys.length === 0) {
      return [`${pad}${renderedKey}: {}`];
    }
    return [`${pad}${renderedKey}:`, ...yamlObjectLines(record, indent + 2)];
  }
  return [`${pad}${renderedKey}: null`];
}

function yamlArrayItemLines(value: unknown, indent: number): string[] {
  const pad = " ".repeat(indent);
  if (isScalar(value)) {
    return [`${pad}- ${yamlScalar(value)}`];
  }
  const record = recordValue(value);
  if (record !== undefined) {
    return [`${pad}-`, ...yamlObjectLines(record, indent + 2)];
  }
  return [`${pad}- null`];
}

function yamlKey(key: string): string {
  return /^[A-Za-z_][A-Za-z0-9_-]*$/.test(key) ? key : JSON.stringify(key);
}

function yamlScalar(value: string | number | boolean | null): string {
  if (typeof value === "string") {
    return JSON.stringify(value);
  }
  if (value === null) {
    return "null";
  }
  return `${value}`;
}

function isScalar(value: unknown): value is string | number | boolean | null {
  return value === null || typeof value === "string" || typeof value === "number" || typeof value === "boolean";
}

function stableJson(value: unknown): string {
  return `${JSON.stringify(canonicalJson(value), null, 2)}\n`;
}

function canonicalJson(value: unknown): unknown {
  if (Array.isArray(value)) {
    return value.map(canonicalJson);
  }
  const record = recordValue(value);
  if (record !== undefined) {
    return Object.fromEntries(Object.keys(record).sort(compareString).map((key) => [key, canonicalJson(record[key])]));
  }
  return value;
}

function isUnderRoot(root: string, candidate: string): boolean {
  const relativePath = relative(resolve(root), resolve(candidate));
  return relativePath === "" || (!relativePath.startsWith("..") && !isAbsolute(relativePath));
}

function uniqueSorted(values: readonly string[]): string[] {
  return [...new Set(values)].sort(compareString);
}

function compareString(left: string, right: string): number {
  return left.localeCompare(right);
}
