/**
 * PROTOTYPE — THROWAWAY. PNG → terminal half-block sprite baker.
 *
 * Reads pixel-art PNGs from proto/assets/, downscales to a coarse cell grid
 * (nearest-neighbor via ffmpeg), and bakes proto/tui/pixel-sprites.ts with:
 *  - `cells`: [topHex|null, bottomHex|null][][] for OpenTUI rendering
 *  - `ansi`: raw truecolor half-block rows for text-mode surfaces (wizard)
 *
 * Usage: bun scripts/px2ansi.ts
 */
import { existsSync } from "node:fs";
import { join } from "node:path";

interface SpriteSpec {
  name: string;
  file: string;
  /** target width in pixels (= terminal columns); height matches source ratio */
  size: number;
}

const SPECS: SpriteSpec[] = [
  { name: "sprigIdle", file: "sprig-idle.png", size: 16 },
  { name: "sprigCelebrate", file: "sprig-celebrate.png", size: 16 },
  { name: "bossGoodbyeGreeter", file: "boss-goodbye-greeter.png", size: 20 },
  { name: "emblemUnlock", file: "emblem-unlock.png", size: 12 },
  { name: "emblemBoss", file: "emblem-boss.png", size: 12 },
  { name: "heart", file: "heart.png", size: 10 },
  { name: "door", file: "door.png", size: 12 },
  { name: "medal", file: "medal.png", size: 12 },
  { name: "coin", file: "coin.png", size: 10 },
  { name: "minerDrill", file: "machine-miner.png", size: 16 },
  { name: "routingBelt", file: "machine-belt.png", size: 16 },
  { name: "assembler", file: "machine-assembler.png", size: 16 },
  { name: "circuitPole", file: "machine-circuit.png", size: 16 },
  { name: "orePatch", file: "ore-patch.png", size: 12 },
  { name: "powerBolt", file: "power-bolt.png", size: 10 },
];

const ASSETS = join(import.meta.dir, "..", "proto", "assets");
const OUT = join(import.meta.dir, "..", "proto", "tui", "pixel-sprites.ts");

/** near-black is treated as transparent (sprites are generated on #000) */
const TRANSPARENT_MAX = 26;

async function decode(file: string, size: number): Promise<{ px: Uint8Array; w: number; h: number }> {
  const proc = Bun.spawn(
    [
      "ffmpeg",
      "-v", "error",
      "-i", file,
      "-vf", `scale=${size}:${size}:flags=neighbor`,
      "-f", "rawvideo",
      "-pix_fmt", "rgba",
      "-",
    ],
    { stdout: "pipe", stderr: "pipe" },
  );
  const bytes = new Uint8Array(await new Response(proc.stdout).arrayBuffer());
  if ((await proc.exited) !== 0) {
    throw new Error(`ffmpeg failed for ${file}: ${await new Response(proc.stderr).text()}`);
  }
  if (bytes.length !== size * size * 4) {
    throw new Error(`unexpected byte count for ${file}: ${bytes.length} (want ${size * size * 4})`);
  }
  return { px: bytes, w: size, h: size };
}

function hexAt(px: Uint8Array, w: number, x: number, y: number): string | null {
  const i = (y * w + x) * 4;
  const r = px[i]!;
  const g = px[i + 1]!;
  const b = px[i + 2]!;
  const a = px[i + 3]!;
  if (a < 128) return null;
  if (Math.max(r, g, b) < TRANSPARENT_MAX) return null;
  return `#${r.toString(16).padStart(2, "0")}${g.toString(16).padStart(2, "0")}${b.toString(16).padStart(2, "0")}`;
}

function fg(hex: string): string {
  const [r, g, b] = [hex.slice(1, 3), hex.slice(3, 5), hex.slice(5, 7)].map((v) => Number.parseInt(v, 16));
  return `\x1b[38;2;${r};${g};${b}m`;
}
function bg(hex: string): string {
  const [r, g, b] = [hex.slice(1, 3), hex.slice(3, 5), hex.slice(5, 7)].map((v) => Number.parseInt(v, 16));
  return `\x1b[48;2;${r};${g};${b}m`;
}

function toAnsiRow(cells: Array<[string | null, string | null]>): string {
  let out = "";
  for (const [top, bottom] of cells) {
    if (top === null && bottom === null) out += "\x1b[0m ";
    else if (top !== null && bottom !== null) out += `${fg(top)}${bg(bottom)}▀`;
    else if (top !== null) out += `\x1b[0m${fg(top)}▀`;
    else out += `\x1b[0m${fg(bottom!)}▄`;
  }
  return `${out}\x1b[0m`;
}

const sprites: Record<string, { width: number; cellRows: Array<Array<[string | null, string | null]>>; ansi: string[] }> = {};

for (const spec of SPECS) {
  const file = join(ASSETS, spec.file);
  if (!existsSync(file)) {
    console.error(`MISSING ${file} — skipping ${spec.name}`);
    continue;
  }
  const { px, w, h } = await decode(file, spec.size);
  const cellRows: Array<Array<[string | null, string | null]>> = [];
  for (let y = 0; y < h; y += 2) {
    const row: Array<[string | null, string | null]> = [];
    for (let x = 0; x < w; x += 1) {
      row.push([hexAt(px, w, x, y), y + 1 < h ? hexAt(px, w, x, y + 1) : null]);
    }
    cellRows.push(row);
  }
  // trim fully-empty top/bottom rows for tight sprites
  while (cellRows.length > 0 && cellRows[0]!.every(([t, b]) => t === null && b === null)) cellRows.shift();
  while (cellRows.length > 0 && cellRows.at(-1)!.every(([t, b]) => t === null && b === null)) cellRows.pop();
  sprites[spec.name] = { width: spec.size, cellRows, ansi: cellRows.map(toAnsiRow) };
  console.log(`baked ${spec.name}: ${spec.size}x${cellRows.length * 2}px -> ${cellRows.length} rows`);
}

const banner = `/**
 * PROTOTYPE — THROWAWAY. GENERATED by scripts/px2ansi.ts from proto/assets/*.png
 * (art generated with Codex imagegen). Do not hand-edit; re-run the baker.
 */`;

const body = `${banner}

export type PixelCell = [top: string | null, bottom: string | null];

export interface PixelSprite {
  /** columns */
  width: number;
  /** row-pairs of pixel colors for cell-based renderers */
  cellRows: PixelCell[][];
  /** raw truecolor half-block rows for text-mode surfaces */
  ansi: string[];
}

export const PIXEL_SPRITES = ${JSON.stringify(sprites, null, 2)} as const satisfies Record<string, PixelSprite>;

export type PixelSpriteName = keyof typeof PIXEL_SPRITES;
`;

await Bun.write(OUT, body);
console.log(`wrote ${OUT}`);
